### ISSUE TITLE
Update Electron peer dependency to 1.8

### ISSUE THREAD

**Issue by Rudloff** [webcatalog/electron-widevinecdm#10]
`yarn check` complains that electron-widevinecdm requires Electron 1.7:
```
error "electron-widevinecdm#electron@1.7.x" doesn't satisfy found match of "electron@1.8.2"
```
but it seems to work correctly with Electron 1.8.

Would it be possible to update `peerDependencies` to accept 1.8 as well?

**Comment by quanglam2807** [comment]
@Rudloff I'll try to update that soon. But actually, we would need a newer version of WidevineCDM. (Electron 1.7 uses Chrome 58, Electron 1.8 uses Chrome 59). Still, I can't find a good place to download extractable Chrome 59 setup file for Windows. 

Currently, I'm using https://www.slimjet.com/chrome/google-chrome-old-version.php but the files only work with 7zip up to Chrome 58 :(

> The old versions of Chrome before V58 are packed as 7zip self-extracting executable. Just run the executable and extract the files under any folder on your hard drive. Then launch Google chrome with chrome.exe under the extraction folder. After V59, the archived chrome old version files are official Chrome offline installers. Just uninstall any current version of Chrome first and then run the downloaded installer. It's a one-click installer without any interactive UI.

**Comment by quanglam2807** [comment]
I may drop `win32` support. Certainly, the current binaries may work with Electron 1.8 but it's too risky. Considering this statement:
> Note: The major version of Chrome browser has to be the same with the Chrome version used by Electron, otherwise the plugin will not work even though navigator.plugins would show it has been loaded. https://electronjs.org/docs/tutorial/using-widevine-cdm-plugin

**Comment by quanglam2807** [comment]
https://github.com/quanglam2807/electron-widevinecdm/releases/tag/v6.0.0

**Comment by Rudloff** [comment]
That was quick, thanks!
