### ISSUE TITLE
Client side plugin download

### ISSUE THREAD

**Issue by tomasmcm** [webcatalog/electron-widevinecdm#2]
Hi there,
I was thinking about using this for an App I'm building.
Would it be possible to run the install.js script on the client side instead of post-install? That way the first time a user opens the app it would download the correct plugin version and then load it.

**Comment by quanglam2807** [comment]
@tomasmcm So I would modify the code to download the binary for all 3 platforms. When you first start the code, it will try to check for update, download the new binary if available, save to user data folder. The next time you launch the app, it will try to load the binary from user data. Does it sound good for you?

**Comment by tomasmcm** [comment]
@quanglam2807 For development purposes having a way to download all binaries would be nice.

However, for license reasons, the best approach would be to not include the plugins with the app release and download them when the user first opens the app (or check on app start if the plugins are present or not).

**Comment by quanglam2807** [comment]
@tomasmcm But what if the user launches the website before the binaries are downloaded and loaded? Of course, I can make a blocking request but I don't think it's a good idea.

**Comment by tomasmcm** [comment]
@quanglam2807 I guess if there is a callback from load when the user doesn't have the binaries to trigger the download I could add a "Please wait while setup finishes" information or something... and when the binaries are downloaded we just reload the electron app.

**Comment by quanglam2807** [comment]
@tomasmcm I'll work on this next month.

**Comment by quanglam2807** [comment]
@tomasmcm Do you know if there's a way to download the plugin files directly from Google?

**Comment by quanglam2807** [comment]
@tomasmcm Added with https://github.com/webcatalog/electron-widevinecdm/releases/tag/v2.0.0
