### ISSUE TITLE
Problem with Binary Build with electron-builder

### ISSUE THREAD

**Issue by simonjenny** [webcatalog/electron-widevinecdm#3]
Hi,

The Plugin works fine, when I start the App from "npm start" but after packaging the App for Darwin (Mac) the Plugin is not available in Netflix an throws the usual error.

**Comment by quanglam2807** [comment]
@simonjenny That's strange. What do you use to package your app? `electron-builder`?

**Comment by simonjenny** [comment]
Yes I use "electron-builder" Version "^8.6.0"

**Comment by quanglam2807** [comment]
@simonjenny What's about your `electron` version? Maybe the binaries are not compatible with your Chromium version.

**Comment by simonjenny** [comment]
I use "electron": "^1.6.6"

**Comment by simonjenny** [comment]
I have uploaded the project to https://github.com/simonjenny/netflix-electron maybe this will make it easier to debug.

**Comment by quanglam2807** [comment]
@simonjenny Can you test WebCatalog, please? I don't have a Netflix account.

**Comment by quanglam2807** [comment]
@simonjenny  It should be fixed with https://github.com/webcatalog/electron-widevinecdm/releases/tag/v2.0.0
