### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by QuadDepo** [webcatalog/electron-widevinecdm#5]
When i try to build my Electron app i get this error

`ERROR in ./~/electron-widevinecdm/src/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../package in /Users/george/Desktop/React/always-on-top/node_modules/electron-widevinecdm/src
 @ ./~/electron-widevinecdm/src/index.js 6:16-37`

any idea?

**Comment by quanglam2807** [comment]
@QuadDepo What version of Electron are you using? It looks like the code fails to load the `package.json`

https://github.com/webcatalog/electron-widevinecdm/blob/master/src/index.js#L6

I'll try to make a hot fix ASAP.

**Comment by quanglam2807** [comment]
Fixed with 3.0
