### ISSUE TITLE
Cannot watch Netflix anymore

### ISSUE THREAD

**Issue by mdnahian** [webcatalog/electron-widevinecdm#8]
I get the following error when attempting to watch something on Netflix:

`Uncaught Error: attempting to use ShaktiProperties before the properties client has been initialized.
This may mean you should defer your require until needed vs at the top of file.`

**Comment by ghost** [comment]
@mdnahian Same problem here, it asks me every time to update WidevineCDM.

By typing `navigator.plugins` in the console I got this result :

![simpleflix](https://user-images.githubusercontent.com/31095928/31562572-494c87ba-b05c-11e7-88e0-cc9d66234660.png)

Any solution about this @quanglam2807 ?

**Comment by quanglam2807** [comment]
@UnSimpleGeek Can you guys try the latest version?

**Comment by ghost** [comment]
@quanglam2807 I have updated everything in my Electron application, but I still have the same message. It seems like the plugin is not loaded at all.

My Electron application : https://github.com/UnSimpleGeek/Simpleflix

**Comment by quanglam2807** [comment]
@UnSimpleGeek The libs are not included with the package. You need to download it first. https://github.com/webcatalog/electron-widevinecdm/blob/master/example/main.js#L41

**Comment by ghost** [comment]
@quanglam2807 Even using your example it doesn't work.

Here is a Pastebin using your example : https://pastebin.com/YRf2MZhv

I have only modified the line 11 to load your module.

**Comment by quanglam2807** [comment]
@UnSimpleGeek The first time the app opens, it won't work. You need to wait for the plugin do be downloaded and then there'll be a dialog asking for relaunching when the download is finished.

I'll see if I can make it easier.

**Comment by ghost** [comment]
@quanglam2807 Oh thanks, my internet connection is pretty bad... Maybe you can display a loading bar at the bottom of the application ?

**Comment by quanglam2807** [comment]
@quanglam2807 In the past (v1), the libs are included when you install the package from npm but I removed it because Widevine license doesn't allow us to freely do so.

**Comment by ghost** [comment]
@quanglam2807 :confused:

**Comment by ghost** [comment]
@quanglam2807 So, at the moment, is there any way to see the download progress of the plugin ?

**Comment by quanglam2807** [comment]
@UnSimpleGeek No. I'll see if I can rewrite the library.

**Comment by ghost** [comment]
@quanglam2807 Thanks a lot dude !

**Comment by quanglam2807** [comment]
@UnSimpleGeek It should work https://github.com/webcatalog/electron-widevinecdm/releases/tag/v4.0.0

**Comment by ghost** [comment]
@quanglam2807 Do I still need to wait until the plugin is fully downloaded ?

**Comment by quanglam2807** [comment]
@UnSimpleGeek No, you don't. Just check out the new README

**Comment by ghost** [comment]
@quanglam2807 I've already updated my app using the new README but I still got the same error from Netflix...

![netflix](https://user-images.githubusercontent.com/31095928/31854257-10d627d4-b696-11e7-8a31-04a5f18d474a.png)

**Comment by quanglam2807** [comment]
@UnSimpleGeek The plugin is loaded. Which version of Electron are you using?

**Comment by ghost** [comment]
@quanglam2807 Latest one, `1.7.9`.

**Comment by quanglam2807** [comment]
@UnSimpleGeek It seems like the latest version of Widevine is compatible with Electron 1.7.9. Give me some time.

**Comment by ghost** [comment]
@quanglam2807 Sure, take your time !

**Comment by ghost** [comment]
@quanglam2807 Please, can you give me the exact version number of Electron where Widevine work ? My application doesn't really need to have the latest version of the framework installed. Thank you in advance.

**Comment by quanglam2807** [comment]
@UnSimpleGeek Electron 1.7.9 is using Chrome 59. The plugin files in the repo is extracted from Chrome 62. So they are not compatible. :( I'm finding a solution.

**Comment by ghost** [comment]
@quanglam2807 So fetch a previous version of Widevine, with the `1.4.8.1008` it's perfectly working !

**Comment by quanglam2807** [comment]
@UnSimpleGeek I'm working to automate the process.

**Comment by quanglam2807** [comment]
@UnSimpleGeek  @mdnahian Please test v5.0.1 https://github.com/webcatalog/electron-widevinecdm/releases/tag/v5.0.1

**Comment by ghost** [comment]
@quanglam2807 Thanks a lot ! Do I need extra configuration or is it working just like the previous versions ?

**Comment by quanglam2807** [comment]
@quanglam2807 It should work without any changes.
